/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/Account.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Language: typeof import('./components/Language.vue')['default']
    LockPassword: typeof import('./components/LockPassword.vue')['default']
    Menu: typeof import('./components/menu.vue')['default']
    Mynft: typeof import('./components/mynft.vue')['default']
    Onsalenft: typeof import('./components/onsalenft.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletBackup: typeof import('./components/WalletBackup.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
